### ISSUE TITLE
Question about Idiomatic Rust.

### ISSUE THREAD

**Issue by 10thfloor** [MarshallBelles/flow-rust-sdk#2]
Hello, as someone new to Rust, I have a query about borrowing and method calling  syntax for a function that takes a string.

Should the calling syntax of SDK methods that take strings be simplified from, for example: 
```
check_availability(&"grpc://access.devnet.nodes.onflow.org:9000".to_string()).await?;
```
to 
```
check_availability(&"grpc://access.devnet.nodes.onflow.org:9000").await?;
```

If the function definition is modified as such (change the `network_address` parameter from `&String` to `&str` and use `to_owned` method instead of `clone`): 
```
pub async fn check_availability(network_address: &str) -> Result<(), Box<dyn error::Error>> {
    let mut client = AccessApiClient::connect(network_address.to_owned()).await?;

    let request = tonic::Request::new(PingRequest {});

    client.ping(request).await?;

    Ok(())
}
```

Thought about posting on SO, but thought I would come here first, because it's easier to ask when there is some code for context.

**Comment by 10thfloor** [comment]
Haven't read too much Rust code in life, so apologies if this is redundant.

**Comment by MarshallBelles** [comment]
@10thfloor 

In Rust, when you specify a string as "hello world" what you are doing is creating a static non-mutable `str` (utf8 bytes) which has some limitations. [The `String` class is heap-allocated to allow for mutability](https://stackoverflow.com/questions/24158114/what-are-the-differences-between-rusts-string-and-str).

I chose to have a mutable `String` reference so that you only have to define your network_address once, and can make adjustments if needed. (This also makes the reference thread safe).

**Comment by 10thfloor** [comment]
Great. Thanks for the explanation.

**Comment by fee1-dead** [comment]
You could make adjustments with a `String` and convert that to `&str` relatively cheaply. `&str` is not limited to just literals.
